### ISSUE TITLE
Suggestion: Conway's Game of Life

### ISSUE THREAD

**Issue by yoavram** [neozhaoliang/pywonderland#1]
Suggesting another example. 
Here is a good reference for Python code implementing and explaining Conway's Game of Life:
https://jakevdp.github.io/blog/2013/08/07/conways-game-of-life/

**Comment by neozhaoliang** [comment]
Hi Yoavram: thanks for the suggestion. Conway's game of life is interesting, but there are already many implementations on github and I haven't figured out how to make something different with it. Do you have any ideas?

**Comment by neozhaoliang** [comment]
game of life animation is added :smile:
