### ISSUE TITLE
Error when runing e8.py 

### ISSUE THREAD

**Issue by xhtp2000** [neozhaoliang/pywonderland#14]
---> 14 import cairocffi as cairo
     15 import numpy as np
     16 from palettable.colorbrewer.qualitative import Set1_8

C:\Localdata\Software\PythonAnaconda\lib\site-packages\cairocffi\__init__.py in <module>()
     14 import ctypes.util
     15 
---> 16 from . import constants
     17 from .compat import FileNotFoundError
     18 from ._ffi import ffi

ImportError: cannot import name constants

**Comment by neozhaoliang** [comment]
This seems because there are some conflictions in the version of the `cffi` module. I have met this problem when installing the `numba` module. I suggest you run it with python3+, or manully install the `cairocffi` via `pip` command
```bash
pip install cairocffi
```
