### ISSUE TITLE
Missing image in 2d-hyperbolic-tilings

### ISSUE THREAD

**Issue by Daniel-at-github** [neozhaoliang/pywonderland#5]
There is a broken image link in https://github.com/neozhaoliang/pywonderland#2d-hyperbolic-tilings

(Nice images :smile:)

**Comment by neozhaoliang** [comment]
Hi @Daniel-at-github: the two sub-projects (2d hyperbolic tilings and 3d hyperbolic honeycombs) are not completed, and I'm not satisfied with the 2d hyperbolic tiling images I got so far. I need some time to finish them.

**Comment by Daniel-at-github** [comment]
A broken link is somehow strange. You could substitute it for "work in progress", delete it or something you see fit.
